CaMauTravel/Controllers/AttendenceController.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaMauTravel.Controllers
{
    public class AttendenceController : Controller
    {
        // GET: Attendence
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public PartialViewResult PlaceType()
        {
            var model = new PlaceTypeDAO().listAll();
            return PartialView(model);
        }

        public ActionResult PlaceTypeAttraction(int attID, int page = 1, int pageSize = 1)
        {
            var placeType = new PlaceTypeDAO().Detail(attID);
            ViewBag.PlaceType = placeType;
            int totalRecord = 0;
            var model = new TourisAttractionDAO().ListByPlaceType(attID, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.Maxpage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Pre = page - 1;

            return View(model);
        }
        public ActionResult Detail(long id)
        {
            var attraction = new TourisAttractionDAO().Detail(id);
            ViewBag.Detail = new PlaceTypeDAO().Detail(attraction.PlaceTypeID.Value);

            return View(attraction);
        }
    }
}

CaMauTravel/Controllers/ShoptController.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaMauTravel.Controllers
{
    public class ShoptController : Controller
    {
        // GET: Shopt
        public ActionResult Index()
        {
            TourisDAO touris = new TourisDAO();
            ViewBag.ListAll = touris.ListAll();
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult TopHot()
        {
            var model = new TourisDAO().ListHot(5);
            ViewBag.ListHot = model;
            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult RelatedTouris()
        {
            var model = new TourisDAO().ReletedTouris();
            ViewBag.RelatedTouris = model;
            return PartialView(model);
        }

    }
}

CaMauTravel/Views/Attendence/Detail.cshtml
@model Model.EF.TouristAttraction
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>We sale fresh fruits</p>
                    <h1>Detail @Model.Name</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="single-product mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="single-product-img">
                    <img src="@Model.Images" alt="@Model.Name">
                </div>
            </div>
            <div class="col-md-7">
                <div class="single-product-content">
                    <h3>@Model.Name</h3>
                    <p>@Model.Description</p>
                    <div class="single-product-form">
                        <form action="index.html">
                            <input type="number" placeholder="0">
                        </form>
                        <p><strong>Categories: </strong>@Model.PlaceType.Name</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end single product -->
<!-- more products -->
<div class="more-products mb-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="section-title">
                    <h3><span class="orange-text">Related</span> Products</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
                </div>
            </div>
        </div>
        <div class="row">
            @{Html.RenderAction("RelatedTouris", "Shopt");}
        </div>
    </div>
</div>

CaMauTravel/Views/Attendence/PlaceType.cshtml
@model List<Model.EF.PlaceType>
@{
    ViewBag.Title = "PlaceType";
}

<ul class="sub-menu">
    @foreach (var item in Model)
    {
        <li><a href="/attraction/@item.MetaTitle-@item.ID">@item.Name</a></li>
    }
</ul>

CaMauTravel/Views/Attendence/PlaceTypeAttraction.cshtml
@model List<Model.Models.TourisAttractionViewModels>
@{
    var placeType = (Model.EF.PlaceType)ViewBag.PlaceType;
    ViewBag.Title = placeType.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>We sale fresh fruits</p>
                    <h1>Touris</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="product-section mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="section-title">
                    <h3><span class="orange-text">@placeType.Name</span> </h3>
                </div>
            </div>
        </div>
        <div class="row product-lists">
            @foreach (var item in Model)
            {
                var url = "/detail/" + item.MetaTitle + "-" + item.ID;
                <div class="col-lg-4 col-md-6 text-center strawberry">
                    <div class="single-product-item">
                        <div class="product-image">
                            <a href="@url"><img src="@(item.Images??"/Data/null/null.png")" alt="@item.Name"></a>
                        </div>
                        <h3>@item.Name</h3>
                    </div>
                </div>
            }
            <div class="clear"></div>


        </div>
        @if (ViewBag.TotalPage >= 1)
        {
            var pageDisplay = (int)ViewBag.Maxpage;
            int totalPage = (int)ViewBag.TotalPage;
            int currentPage = (int)ViewBag.Page;

            var startIndex = Math.Max(1, currentPage - pageDisplay / 2);
            var endIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

            var link = "/touris/" + placeType.MetaTitle + "-" + placeType.ID;

            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="pagination-wrap">
                        <ul>
                            @if (currentPage > ViewBag.First)
                            {
                                <li><a href="@link?page=@ViewBag.Pre">Prev</a></li>
                                <li><a href="@link?page=@ViewBag.First">Next</a></li>
                            }
                            @for (int i = startIndex; i <= endIndex; i++)
                            {
                                if (currentPage == i)
                                {
                                    <li><a href="@link?page=@i" class="active" title="page @i">@i</a></li>
                                }
                                else
                                {
                                    <li><a href="@link?page=@i" class="pos" title="page @i">@i</a></li>
                                }
                            }
                            @if (currentPage < totalPage)
                            {
                                <li><a href="@link?page=@ViewBag.Next">Prev</a></li>
                                <li><a href="@link?page=@ViewBag.Last">Next</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
        else
        {
            <span> No Data in this Place Type</span>
        }
    </div>
</div>
<!-- end products -->
<!-- logo carousel -->
<div class="logo-carousel-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="logo-carousel-inner">
                    <div class="single-logo-item">
                        <img src="assets/img/company-logos/1.png" alt="">
                    </div>
                    <div class="single-logo-item">
                        <img src="assets/img/company-logos/2.png" alt="">
                    </div>
                    <div class="single-logo-item">
                        <img src="assets/img/company-logos/3.png" alt="">
                    </div>
                    <div class="single-logo-item">
                        <img src="assets/img/company-logos/4.png" alt="">
                    </div>
                    <div class="single-logo-item">
                        <img src="assets/img/company-logos/5.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>