CaMauTravel/Areas/Admin/Controllers/TouristAttractionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaMauTravel.Common;
using Model.DAO;
using Model.EF;
using PagedList;

namespace CaMauTravel.Areas.Admin.Controllers
{
    public class TouristAttractionsController : BaseController
    {
        private CaMauTravelDBContext db = new CaMauTravelDBContext();

        // GET: Admin/TouristAttractions
        public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            var dao = new TourisAttractionDAO();
            var model = dao.ListAllPaging(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }

        // GET: Admin/TouristAttractions/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristAttraction touristAttraction = db.TouristAttractions.Find(id);
            if (touristAttraction == null)
            {
                return HttpNotFound();
            }
            return View(touristAttraction);
        }

        // GET: Admin/TouristAttractions/Create
        public ActionResult Create()
        {
            ViewBag.PlaceTypeID = new SelectList(db.PlaceTypes, "ID", "Name");

            return View();
        }

        // POST: Admin/TouristAttractions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Images,Description,PlaceTypeID,MetaTitle")] TouristAttraction touristAttraction)
        {
            if (ModelState.IsValid)
            {
                touristAttraction.CreateDate = DateTime.Now;
                touristAttraction.Status = true;
                touristAttraction.ParentID = 1;
                touristAttraction.DisplayOrder = 1;
                db.TouristAttractions.Add(touristAttraction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlaceTypeID = new SelectList(db.PlaceTypes, "ID", "Name");
            return View(touristAttraction);
        }

        public ActionResult CreateAndEditMultiTouris(int id = 0)
        {
            TourisAttrDetail tourisAttrDetail = new TourisAttrDetail();
            using (CaMauTravelDBContext CMD = new CaMauTravelDBContext())
            {
                if (id != 0)
                {
                    tourisAttrDetail = CMD.TourisAttrDetails.Where(x => x.ID == id).FirstOrDefault();

                    tourisAttrDetail.SelectedIDArray = tourisAttrDetail.SelectTourisAttraction.Split(',').ToArray();
                }
                tourisAttrDetail.DetailCollection = CMD.TouristAttractions.ToList();
            }

            return View(tourisAttrDetail);
        }

        [HttpPost]
        public ActionResult CreateAndEditMultiTouris(TourisAttrDetail tourisAttrDetail)
        {
            tourisAttrDetail.SelectTourisAttraction = string.Join(",", tourisAttrDetail.SelectedIDArray);
            using (CaMauTravelDBContext CMD = new CaMauTravelDBContext())
            {
                if (tourisAttrDetail.ID == 0)
                {
                    CMD.TourisAttrDetails.Add(tourisAttrDetail);
                    CMD.SaveChanges();
                }
                else
                {
                    db.Entry(tourisAttrDetail).State = EntityState.Modified;
                }
                db.SaveChanges();
            }
            return RedirectToAction("CreateAndEditMultiTouris", new { id = 0 });
        }

        // GET: Admin/TouristAttractions/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristAttraction touristAttraction = db.TouristAttractions.Find(id);
            if (touristAttraction == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlaceTypeID = new SelectList(db.PlaceTypes, "ID", "Name", touristAttraction.PlaceTypeID);
            return View(touristAttraction);
        }

        // POST: Admin/TouristAttractions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Images,Description,PlaceTypeID,MetaTitle,ParentID,DisplayOrder,SeoTitle,CreateDate,MetaWords,MetaDescription,Status")] TouristAttraction touristAttraction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(touristAttraction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlaceTypeID = new SelectList(db.PlaceTypes, "ID", "Name", touristAttraction.PlaceTypeID);
            return View(touristAttraction);
        }

        // GET: Admin/TouristAttractions/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristAttraction touristAttraction = db.TouristAttractions.Find(id);
            if (touristAttraction == null)
            {
                return HttpNotFound();
            }
             ViewBag.PlaceTypeID = new SelectList(db.PlaceTypes, "ID", "Name", touristAttraction.PlaceTypeID);
            return View(touristAttraction);
        }

        // POST: Admin/TouristAttractions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            TouristAttraction touristAttraction = db.TouristAttractions.Find(id);
            db.TouristAttractions.Remove(touristAttraction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public JsonResult ChangeStatus(long id)
        {
            var result = new TourisAttractionDAO().ChangeStatus(id);

            return Json(new
            {
                status = result
            }); ;
        }
    }
}

CaMauTravel/Controllers/TourisAttractionsController.cs
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaMauTravel.Controllers
{
    public class TourisAttractionsController : Controller
    {
        // GET: TourisAttendences
        public ActionResult Index()
        {
            TourisAttractionDAO dao = new TourisAttractionDAO();
            ViewBag.ListAll = dao.getTouris();

            return View();
        }

        public ActionResult Detail(long id)
        {
            var touris = new TourisAttractionDAO().Detail(id);
            ViewBag.Detail = new PlaceTypeDAO().Detail(touris.PlaceTypeID.Value);

            return View(touris);
        }
    }
}

CaMauTravel/Areas/Admin/Views/TouristAttractions/Create.cshtml
@model Model.EF.TouristAttraction

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section JsFooter{
    <script>
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
    </script>
}

<main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://meta.vn/Data/image/2021/09/30/background-la-gi-anh-background-dep-28.jpg');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 mx-auto">
                    <div class="card z-index-0 fadeIn3 fadeInBottom">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                            <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">New</h4>
                            </div>
                            <div class="card-body">
                                @using (Html.BeginForm(new { @class = "text-start" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="input-group input-group-outline my-3">

                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Name" } })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                                        </div>

                                        <div class="input-group input-group-outline my-3">

                                            @Html.TextBoxFor(model => model.Images, new { htmlAttributes = new { @class = "form-control", placeholder = "Image" }, id = "txtImage" })
                                            <a id="btnSelectImage" href="#"> Choose Images </a>
                                            @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })

                                        </div>

                                        <div class="input-group input-group-outline my-3">

                                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Description" } })
                                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                                        </div>

                                        <div class="input-group input-group-outline my-3">
                                            @Html.LabelFor(model => model.PlaceTypeID, "PlaceTypeID", htmlAttributes: new { @class = "control-label col-md-12" })
                                            @Html.DropDownList("PlaceTypeID", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.PlaceTypeID, "", new { @class = "text-danger" })
                                        </div>


                                        <div class="input-group input-group-outline my-3">

                                            @Html.EditorFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control", placeholder = "Metatitle" } })
                                            @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })

                                        </div>

                                        <div class="text-center">
                                            <input type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2" value="Submit" />
                                            <button type="button" class="btn bg-gradient-primary w-100 my-4 mb-2">@Html.ActionLink("Back to List", "Index")</button>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</main>
<!--   Core JS Files   -->
<script src="~/Assets/Admin/js/core/popper.min.js"></script>
<script src="~/Assets/Admin/js/core/bootstrap.min.js"></script>
<script src="~/Assets/Admin/js/plugins/perfect-scrollbar.min.js"></script>
<script src="~/Assets/Admin/js/plugins/smooth-scrollbar.min.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="~/Assets/Admin/js/material-dashboard.min.js?v=3.0.2"></script>

CaMauTravel/Areas/Admin/Views/TouristAttractions/CreateAndEditMultiTouris.cshtml
@model Model.EF.TourisAttrDetail
@{
    ViewBag.Title = "CreateAndEditMultiTouris";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section JsFooter{
    <script>
        $(function () {
            $("#multiSelectDropdown").chosen({
                width: "100%"
            });
        });
    </script>
}


<main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://meta.vn/Data/image/2021/09/30/background-la-gi-anh-background-dep-28.jpg');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 mx-auto">
                    <div class="card z-index-0 fadeIn3 fadeInBottom">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                            <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Create New Attraction Detail</h4>
                            </div>
                            <div class="card-body">
                                @using (Html.BeginForm())
                                {
                                    <div class="form-horizontal">
                                        @Html.HiddenFor(model => model.ID)
                                        <label>Select Tour Attractions</label>

                                        @Html.ListBoxFor(model => model.SelectedIDArray, new MultiSelectList(Model.DetailCollection, "Name", "Name"), new { id = "multiSelectDropdown", multiple = "true" })
                                        <input type="submit" name="name" value="Submit" />
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</main>
<!--   Core JS Files   -->

<script src="~/Assets/Admin/js/chosen.jquery.min.js"></script>
<script src="~/Assets/Admin/js/core/popper.min.js"></script>
<script src="~/Assets/Admin/js/core/bootstrap.min.js"></script>
<script src="~/Assets/Admin/js/plugins/perfect-scrollbar.min.js"></script>
<script src="~/Assets/Admin/js/plugins/smooth-scrollbar.min.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="~/Assets/Admin/js/material-dashboard.min.js?v=3.0.2"></script>

CaMauTravel/Areas/Admin/Views/TouristAttractions/Delete.cshtml
@model Model.EF.TouristAttraction

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TouristAttraction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceTypeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceTypeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeoTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeoTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaWords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaWords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CaMauTravel/Areas/Admin/Views/TouristAttractions/Details.cshtml
@model Model.EF.TouristAttraction

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid px-2 px-md-4">
    <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('https://images.unsplash.com/photo-1531512073830-ba890ca4eba2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80');">
        <span class="mask  bg-gradient-primary  opacity-6"></span>
    </div>
    <div class="card card-body mx-3 mx-md-4 mt-n6">
        <div class="row gx-4 mb-2">
            <div class="col-auto">
                <div class="avatar avatar-xl position-relative">
                    <img src="@(Model.Images??"/Data/null/null.png")" alt="profile_image" class="w-100 border-radius-lg shadow-sm">
                </div>
            </div>
            <div class="col-auto my-auto">
                <div class="h-100">
                    <h5 class="mb-1">
                        @Html.DisplayFor(model => model.Name)
                    </h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 my-sm-auto ms-sm-auto me-sm-0 mx-auto mt-3">
                <div class="nav-wrapper position-relative end-0">
                    <ul class="nav nav-pills nav-fill p-1" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link mb-0 px-0 py-1 " href="@Url.Action("Index", "TourisAttraction")">
                                <i class="fas fa-chevron-left text-secondary text-sm"></i>
                                <span class="ms-1">Back To List</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="row">
                <div class="col-12 col-xl-12">
                    <div class="card card-plain h-100">
                        <div class="card-header pb-0 p-3">
                            <div class="row">
                                <div class="col-md-8 d-flex align-items-center">
                                    <h6 class="mb-0">Profile Information</h6>
                                </div>
                                <div class="col-md-4 text-end">
                                    <a href="@Url.Action("Edit", "TourisAttraction", new { id = Model.ID })">
                                        <i class="fas fa-user-edit text-secondary text-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Profile"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="card-body p-3">
                            <p class="text-sm">
                                @Html.DisplayFor(model => model.Description)
                            </p>
                            <hr class="horizontal gray-light my-4">
                            <ul class="list-group">

                                <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">@Html.DisplayNameFor(model => model.MetaTitle):</strong> &nbsp; @Html.DisplayFor(model => model.MetaTitle)</li>
                                <strong class="text-dark text-sm">Social:</strong> &nbsp;
                                    <a class="btn btn-facebook btn-simple mb-0 ps-1 pe-2 py-0" href="javascript:;">
                                        <i class="fab fa-facebook fa-lg"></i>
                                    </a>
                                    <a class="btn btn-twitter btn-simple mb-0 ps-1 pe-2 py-0" href="javascript:;">
                                        <i class="fab fa-twitter fa-lg"></i>
                                    </a>
                                    <a class="btn btn-instagram btn-simple mb-0 ps-1 pe-2 py-0" href="javascript:;">
                                        <i class="fab fa-instagram fa-lg"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CaMauTravel/Areas/Admin/Views/TouristAttractions/Index.cshtml
@model PagedList.IPagedList<Model.EF.TouristAttraction>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}


@section JsFooter{
    <script src="~/Assets/Admin/js/controller/tourisAttController.js"></script>
}


<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                        <h6 class="text-white text-capitalize ps-3">Touris Attractions Table</h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="card-header text-center">
                            <button type="button" class="btn bg-gradient-primary btn-sm mt-0 mb-0">@Html.ActionLink("Create New", "Create", new { @class = "text-decoration: none" })</button>
                            <button type="button" class="btn bg-gradient-primary btn-sm mt-0 mb-0">@Html.ActionLink("Create Attraction Detals", "CreateAndEditMultiTouris", new { @class = "text-decoration: none" })</button>
                        </div>
                        @*<div class="card-header text-center">
                                <button type="button" class="btn bg-gradient-primary btn-sm mt-0 mb-0">@Html.ActionLink("Create Attraction Detals", "CreateAndEditMultiTouris", new { @class = "text-decoration: none" })</button>
                            </div>*@
                    </div>
                    <div class="col-6">
                        @using (Html.BeginForm("Index", "TourisAttractions", FormMethod.Get))
                        {
                            <div class="card-header text-center">
                                <div class="input-group input-group-outline">
                                    <input type="text" class="form-control" value="@ViewBag.SearchString" name="searchString" placeholder="Search..">
                                    <button type="submit" class="btn bg-gradient-secondary btn-sm mt-0 mb-0">Find</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="card-body px-0 pb-2 ">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Name</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Description</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Status</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Place Type</th>
                                    <th class="text-center text-secondary text-xxs font-weight-bolder opacity-7">Meta Tile</th>

                                    <th class="text-secondary opacity-7"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <div class="d-flex px-2 py-1">
                                                <div>
                                                    <img src="@(item.Images??"/Data/null/null.png")" class="avatar avatar-sm me-3 border-radius-lg" alt="user1">
                                                </div>
                                                <div class="d-flex flex-column justify-content-center">
                                                    <h6 class="mb-0 text-sm">@Html.DisplayFor(modelItem => item.Name)</h6>

                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <p class="text-xs font-weight-bold mb-0">@Html.DisplayFor(modelItem => item.Description)</p>

                                        </td>
                                        <td class="align-middle text-center text-sm">
                                            <a href="#" class="btn-active" data-id="@item.ID">@(item.Status ? "Enable" : "Disable")</a>
                                        </td>

                                        <td class="align-middle text-center">
                                            <span class="text-secondary text-xs font-weight-bold">@Html.DisplayFor(modelItem => item.PlaceTypeID)</span>
                                        </td>
                                        <td class="align-middle text-center">
                                            <span class="text-secondary text-xs font-weight-bold">@Html.DisplayFor(modelItem => item.MetaTitle)</span>
                                        </td>

                                        <td class="align-middle">
                                            <a href="@Url.Action("Details", "TouristAttractions", new { id = item.ID })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                                Details
                                            </a>
                                        </td>
                                        <td class="align-middle">
                                            <a href="@Url.Action("Edit", "TouristAttractions", new { id = item.ID })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                                Edit
                                            </a>
                                        </td>
                                        <td class="align-middle">
                                            <a href="@Url.Action("Delete", "TouristAttractions", new { id = item.ID })" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                                Delete
                                            </a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                        <ul class="pagination justify-content-center">
                            <li class="page-item"><a>@Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString, @class = "page-link" }))</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>